movie_folder/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:mid>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:mid>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie_folder/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_folder/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=100)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    gen=models.CharField(max_length=250)
    def __str__(self):
        return self.name

movie_folder/movieproject/movieapp/forms.py
from django import forms
from .models import movie

class movieupform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img','gen']

movie_folder/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from . forms import movieupform
# Create your views here.
def index(request):
    movies=movie.objects.all()
    context={
        'movielist':movies
    }
    return render(request,'index.html',context)

def detail(request,mid):
    m=movie.objects.get(id=mid)
    return render(request,"detail.html",{'key':m})

def add(request):
    if request.method == 'POST':
        name=request.POST.get('mname')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        image = request.FILES['img']
        genre=request.POST['mgen']
        movies=movie(name=name,desc=desc,year=year,img=image,gen=genre)
        movies.save()
        return redirect('/')
    return render(request,"add.html")

def update(request,mid):
    movies=movie.objects.get(id=mid)
    form=movieupform(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'m':movies})

def delete(request,id):
    if request.method == 'POST':
        mov=movie.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request,"delete.html")

movie_folder/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="text-align:center;background-color:white;margin-top:2%;">
  <form  method="POST" enctype="multipart/form-data" style="text-align:center;">
  <h1>ADD MOVIES</h1><br>
  {% csrf_token %}
  <input type="text" name="mname" id="" placeholder="Movie name"><br><br>
  <input type="text" name="mgen" id="" placeholder="Movie genre"><br><br>
  <input type="text" name="desc" id="" placeholder="description"><br><br>
  <input type="text" name="year" id="" placeholder="year"><br><br>
  <input type="file" name="img" id=""><br><br>
  <input type="submit" value="Add">
</form>
</div>
{% endblock %}

movie_folder/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movies<span>Mania</span>
  </a>
    <a class="btn btn-warning" href="{% url 'movieapp:add' %}">ADD MOVIE</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_folder/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="text-align:center;">
  <form method="POST">
  {% csrf_token %}
  <h3 style="color:white;">Do you want to delete this movie?</h3><br>
  <input type="submit" value="Yes">
</form>
</div>
{% endblock %}

movie_folder/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="padding:2%;background:white;margin-top:2%;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{key.img.url}}" width="400" height="400">
        </div>
        <div class="col-md-6">
            <h4>Movie : {{key.name}}</h4>
            <h5>year : {{key.year}}</h5>
            <h5>Genre : {{key.gen}}</h5>
            <h6>{{key.desc}}</h6><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' key.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' key.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

movie_folder/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="text-align:center;background-color:white;margin-top:2%;">
  <form method="POST" enctype="multipart/form-data" style="text-align:center;">
    <h1>Update movie</h1><br>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Update">
  </form>
</div>
{% endblock %}

movie_folder/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container" style="margin-top:2%;">
    <div class="row" style="margin-bottom:2%;">
        {% for i in movielist %}
        <div class="col-md-3" style="margin-right: 8%;margin-bottom:4%;">
            <div class="card" style="width: 18rem;">
              <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200" height="200">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">{{i.gen}}</p>
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">view</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}