shopfolder/shopproject/cartapp/urls.py
from django.urls import path
from . import views
app_name='cartapp'

urlpatterns=[
    path('add/<int:pid>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:pid>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:pid>/',views.full_remove,name='full_remove'),



]

shopfolder/shopproject/searchapp/urls.py
from django.urls import path
from . import views
app_name='searchapp'

urlpatterns=[
    path('',views.searchResult,name='searchResult'),


]

shopfolder/shopproject/shopapp/urls.py
from django.urls import path,include
from . import views
app_name='shopapp'

urlpatterns = [
    path('',views.allproductcat,name='allproductcat'),
    path('<slug:c_slug>/',views.allproductcat,name='productsbycategory'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatDetail'),
]

shopfolder/shopproject/shopproject/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shopapp.urls')),
    path('/searchapp/',include('searchapp.urls')),
    path('/cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopfolder/shopproject/cartapp/models.py
from django.db import models
from shopapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shopfolder/shopproject/shopapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shopapp:productsbycategory',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('shopapp:prodCatDetail',args=[self.category.slug,self.slug])


    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

shopfolder/shopproject/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import Product
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,pid):
    product=Product.objects.get(id=pid)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cartapp:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=cart_item.product.price * cart_item.quantity
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,pid):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=pid)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')

def full_remove(request,pid):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=pid)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

shopfolder/shopproject/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Product
from django.db.models import Q



def searchResult(request):
    products=None
    query=None
    if request.method == 'GET':
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})
    else:
        return render(request, 'search.html', {'query': query, 'products': products})

shopfolder/shopproject/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator,EmptyPage,InvalidPage
from shopapp.models import Product, Category


# Create your views here.
# def index(request):
#     return HttpResponse("hey")


def allproductcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

shopfolder/shopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital@0;1&family=IBM+Plex+Sans+Condensed:ital@0;1&family=IBM+Plex+Sans:ital,wght@0,100;0,700;1,100;1,400;1,700&family=IBM+Plex+Serif:ital@0;1&family=Poppins:ital,wght@0,200;0,300;0,500;1,100&family=Raleway:wght@100;400&display=swap" rel="stylesheet">
    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container" style="min-height:92vh;">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

shopfolder/shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to ZeeShop My Cart.....
{% endblock %}
{% block title %}
  Cart - ZeeShop Company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
      <br>
      <h1 class="text-center my_title">Your Cart is empty</h1>
      <br>
    <p class="text-center">Please Click <a href="{% url 'shopapp:allproductcat' %}"> Here</a> to continue</p>
  </div>
</div>
{% else %}
<div>
  <div class="text-center">
      <br>
      <h1 class="text-center my_title">Your Shopping cart</h1>
      <br>
  </div>
</div>
<div class="row mx-auto">
   <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
     <table class="table my_table">
        <thead class="my_thead">
          <tr>
            <th colspan="5">Your Items</th>
          </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <td>
            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded" width="150"></a>
          </td>
          <td class="text-left">
            {{cart_item.product.name}}
            <br>
            PID: {{cart_item.product.id}}
            <br>
            Price: $ {{cart_item.product.price}}
            <br>
            Qty: {{cart_item.quantity}} x $ {{cart_item.name}}
          </td>
          <td>
            $ {{cart_item.sub_total}}
          </td>
          {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fas fa-plus custom_icon"></i></a>
                &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                &nbsp; <a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash custom_icon"></i></a>
            </td>
          {% else %}
            <td>
                &nbsp; <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i></a>
                &nbsp; <a href="{% url 'cartapp:full_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-trash custom_icon"></i></a>
            </td>
            {% endif %}
        </tr>

        {% endfor %}
        </tbody>
     </table>
   </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_table">
            <thead class="my_thead">
                <tr>
                    <th>Checkout</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Please review your cart items before proceeding with the order payment.</td>
                </tr>
                <tr>
                    <td class="text-left">Your Total is : <strong> {{total}}</strong></td>
                </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shopapp:allproductcat' %}" class="btn btn-secondary btn-block my_custom_btn">Continue shopping</a>
            <a href="{% url 'shopapp:allproductcat' %}" class="btn btn-secondary btn-block my_custom_btn">Make Payement</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

shopfolder/shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
    {{ category.description|truncatewords:153 }}
  {% else %}
    Welcome to ZeeShop Where you can buy Anything.....
  {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
    {{ category.name }} -- ZeeShop
  {% else %}
    See our New Collections - ZeeShop
  {% endif %}
{% endblock %}
{% block content %}
{% if category %}
  <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'shopapp:allproductcat' %}">Our Product Collections</a> </p>
            </div>
        </div>
  </div>
{% endif %}
{% if category %}
  <div class="mx-auto" style="text-align:center;">
    <img class="" src="{{category.image.url}}" alt="{{category.name}}">
  </div><br>
 <div>
   <h1 class="text-center my_title">{{category.name}}</h1>
   <p class="text-justify">{{category.description}}</p>
 </div>
{% else %}
<div >
  <img class="my_image my_image_padding" src="{% static 'img/B.png' %}" alt="Our products" width="1300px" height="650px">
</div><br>
<div>
  <h1 class="text-center">Our products collections</h1>
  <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center my-4 p-2" style="width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="400" height="350"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}


        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %} ">{{pg}}</a>

            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

shopfolder/shopproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; ZeeShop pvt ltd. All rights Reserved</p>
</div>

shopfolder/shopproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shopapp:allproductcat' %}"><img src="{% static 'img/log.jpeg' %}" alt="logoimage" width="130" height="130"></a>
  </center>
</header>

shopfolder/shopproject/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shopapp:allproductcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url  'shopapp:allproductcat' %}">All products</a></li>
            {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cartapp:cart_detail' %}"><i class="fa fa-shopping-cart"></i> ({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex"  action="{% url 'searchapp:searchResult' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

shopfolder/shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{ product.description|truncatewords:153 }}
{% endblock %}
{% block title %}
  {% if category %}
    {{ product.name }} -- ZeeShop
  {% endif %}
{% endblock %}
{% block content %}
<div class="row my_product">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allproductcat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div><br>
<div class="container p-4" style="min-height:55vh;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem;">
                <img src="{{product.image.url}}" alt="{{product.name}}" width="300">
            </div>
        </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title"> Product Description</p>
                <p class="text-justify my_prod_text">{{product.description}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                    <a class="btn btn-secondary my-3" href="{% url 'cartapp:add_cart' product.id %}"><i class="fa fa-shopping-cart"></i>  Add to Cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

shopfolder/shopproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    Welcome to ZeeShop Where you can find Anything.....
{% endblock %}
{% block title %}
  Search
{% endblock %}
{% block content %}
<div>
  <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center my-4 p-2" style="width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="400" height="350"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
      {% empty %}
      <div class="row mx-auto">
        <p class="text-center my_search_text">0 results found</p>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}